"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict true.");
console.log(car == 'subaru');
console.log("Is car == 'ford'? I predict false.");
console.log(car == 'ford');
console.log("Is car === 'Subaru'? I predict false.");
console.log(car === 'Subaru');
console.log("Is car != 'honda'? I predict true.");
console.log(car != 'honda');
console.log("Is car !== 'subaru'? I predict false.");
console.log(car !== 'subaru');
console.log("Is car.length > 5? I predict false.");
console.log(car.length > 5);
console.log("Is car.length < 10? I predict true.");
console.log(car.length < 10);
console.log("Is car.startsWith('s')? I predict true.");
console.log(car.startsWith('s'));
console.log("Is car.endsWith('ru')? I predict true.");
console.log(car.endsWith('ru'));
console.log("Is car.includes('ba')? I predict false.");
console.log(car.includes('ba'));
